config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => "registrations" }
  
  resources :users, only: [:show, :index] do
    resources :friend_requests, only: [:create] do
      collection do
        get 'accept'
        get 'decline'
      end
    end
  end

  resources :friend_requests do

  end
  
  resources :posts do
    resources :likes, only: [:create]
  end

  resources :comments do
    resources :likes, only: [:create]
  end

  resources :notifications, only: [:index, :destroy]
  
  root "posts#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index 
    @notifications = current_user.notifications
  end

  def destroy 
    @notification = Notification.find(params[:id])
    @notification.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/views/notifications/index.html.erb
<h4 class='title is-4 has-text-link'>Notifications</h4>

<% if @notifications.length.zero?%>
  <em><%= "no notifications at the moment" %></em>
<% else %>
  <% @notifications.each do |note| %>

    <% sender = note.sender_id.nil? ? 'someone' : User.find(note.sender_id).name %>
    
    <% if note.notice_type == 'comment' %>
      <%= "#{sender} commented on your " %>
      <%= link_to  "post", post_path(notification_source(note, 'comment')) %>
      <%= link_to(notification_path(note), method: :delete, class: 'button is-rounded is-small is-warning is-light ml-2') do %>
        <span class="icon">
          <i class="fa fa-times is-small"></i>
        </span>
      <% end %>
      </br></br>
    <% end %>

    <% if note.notice_type == 'like-comment' %>
      <%= "#{sender} liked your comment on this " %>
      <%= link_to  "post", post_path(notification_source(note, 'like-comment')) %>
      <%= link_to(notification_path(note), method: :delete, class: 'button is-rounded is-small is-warning is-light ml-2') do %>
        <span class="icon">
          <i class="fa fa-times is-small"></i>
        </span>
      <% end %>
      </br></br>
    <% end %>

    <% if note.notice_type == 'like-post' %>
      <%= "#{sender} liked your " %>
      <%= link_to  "post", post_path(notification_source(note, 'like-post')) %>
      <%= link_to(notification_path(note), method: :delete, class: 'button is-rounded is-small is-warning is-light ml-2') do %>
        <span class="icon">
          <i class="fa fa-times is-small"></i>
        </span>
      <% end %>
      </br></br>
    <% end %>  

    <% if note.notice_type == 'friend_request' %>
    <p>
      <% user = notification_source(note, 'friend_request').user %>
      <%= "#{user.name} sent you a"%>
      <%= link_to  "friend request!", users_path %>
      <%= link_to(notification_path(note), method: :delete, class: 'button is-rounded is-small is-warning is-light ml-2') do %>
        <span class="icon">
          <i class="fa fa-times is-small"></i>
        </span>
      <% end %>
      </br></br>
    <% end %>

    <% if note.notice_type == 'friend_accept' %>
      <% user = User.find(notification_source(note, 'friend_accept').friend_id) %>
      <%= link_to  user.name, user_path(user) %>
      <%= " accepted your friend request!"%>
      <%= link_to(notification_path(note), method: :delete, class: 'button is-rounded is-small is-warning is-light ml-2') do %>
        <span class="icon">
          <i class="fa fa-times is-small"></i>
        </span>
      <% end %>
      </br></br>
    <% end %>

  <% end %>
<% end %>