config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => "registrations" }
  
  resources :users, only: [:show, :index] do
    resources :friend_requests, only: [:create] do
      collection do
        get 'accept'
        get 'decline'
      end
    end
  end

  resources :friend_requests do

  end
  
  resources :posts do
    resources :likes, only: [:create]
  end

  resources :comments do
    resources :likes, only: [:create]
  end

  resources :notifications, only: [:index, :destroy]
  
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :posts, class_name: "Post", foreign_key: "author_id",
  dependent: :destroy
  has_many :comments, class_name: "Comment", foreign_key: "author_id"
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_many :sent_requests, -> { where confirmed: false}, class_name: "FriendRequest",
  foreign_key: "user_id"

  has_many :pending_requests, -> { where confirmed: false}, class_name: "FriendRequest",
  foreign_key: "friend_id"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  devise :omniauthable, omniauth_providers: %i[facebook]

  validate :avatar_size

  def friends
    friends_i_sent_inv = FriendRequest.where(user_id: id, confirmed: true).pluck(:friend_id)
    friends_i_received_inv = FriendRequest.where(friend_id: id, confirmed: true).pluck(:user_id)
    ids = friends_i_sent_inv + friends_i_received_inv
    User.where(id: ids)
  end

  def friend_with?(user)
    FriendRequest.confirmed_record?(id, user.id)
  end

  def send_request(user)
    sent_requests.create(friend_id: user.id)
  end

  def possible_friend?(user)
    !FriendRequest.reacted?(id, user.id)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def after_confirmation
    welcome_email
  end

  private

  def avatar_size
    errors.add(:avatar, 'should be smaller than 1MB') if avatar.size > 1.megabytes
  end

  def welcome_email
    UserMailer.welcome_email(self).deliver
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  #skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def index 
    @users = User.all
    @friends = current_user.friends
    @pending_requests = current_user.pending_requests
    @sent_requests = current_user.sent_requests
  end

end

app/views/users/_notification.html.erb
<% if @notifications.length.zero?%>
  <em><%= "no notifications at the moment" %></em>
<% else %>
  <% @notifications.each do |note| %>
    
    <% if note.type == 'comment' %>
      <%= "someone commented on your " %>
      <%= link_to  "post", post_path(notification_source(note, 'comment')) %>
    <% end %>  

    <% if note.type == 'like-comment' %>
      <%= "someone liked your comment on this " %>
      <%= link_to  "post", post_path(notification_source(note, 'like-comment')) %>
    <% end %>

    <% if note.type == 'like-post' %>
      <%= "someone liked your " %>
      <%= link_to  "post", post_path(notification_source(note, 'like-post')) %>
    <% end %>  

    <% if note.type == 'friend_request' %>
      <% user = notification_source(note, 'friend_request').user %>
      <%= "#{user} sent you a friend request!"%>
    <% end %>  

    </br>
    #button logic here 
    <% if note.type == 'friend_request'%>
    #accept/decline buttons + destroy notification
    <% else %>
    #button that destroys notificaiton
    <% end %>
    </br>
  <% end %>
<% end %>

app/views/users/_user_col.html.erb
<%= link_to(user, class: "box has-background-primary-light p-3") do %>
  <article class="media">
    <figure class="media-left">
      <p class="image is-32x32">
        <%= image_tag user.avatar.url, class: 'is-rounded'%>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p class='is-size-7' style='line-height:1.25rem'>
          <strong><%= user.name %></strong>
          <% unless user.handle.nil? %>
          </br><small><%= "@#{user.handle}"%></small>
          <% end %>
        </p>
      </div>
    </div>
  </article>
<% end %>

app/views/users/index.html.erb
<h4 class='title is-4 has-text-link'>Friends</h4>

<% unless @friends.empty?%>
<div class="columns is-multiline">
  <% @friends.each do |friend| %>
  <div class='column is-3-widescreen is-4-desktop is-6-tablet is-12-mobile'>
    <%= render partial: "user_col", object: friend, as: 'user' %>
  </div>
  <% end %>
</div>
<% end %>

<h4 class='title is-4 has-text-link'>Requests</h4>

<% unless @pending_requests.empty? %>
<div class="columns is-multiline">
  <% @pending_requests.each do |req| %>
    <% user = req.user %>
    <div class='column is-3-widescreen is-4-desktop is-6-tablet is-12-mobile'>
    <%= render partial: "user_col", object: user, as: 'user' %>
    <%= link_to(accept_user_friend_requests_path(user_id: user.id, request_id: req.id), class:'button is-rounded is-small is-primary is-light') do %>
      <span class="icon">
        <i class="fa fa-check is-small"></i>
      </span>
    <% end %>
    <%= link_to(decline_user_friend_requests_path(user_id: user.id, request_id: req.id), class:'button is-rounded is-small is-warning is-light') do %>
      <span class="icon">
        <i class="fa fa-times is-small"></i>
      </span>
    <% end %>
  </div>
  <% end %>
</div>
<% end %>

<h4 class='title is-4 has-text-link'>Pending</h4>

<% unless @sent_requests.empty? %>
  <div class="columns is-multiline">
    <% @sent_requests.each do |req| %>
    <% user = req.recipient %>
      <div class='column is-3-widescreen is-4-desktop is-6-tablet is-12-mobile'>
        <%= render partial: "user_col", object: user, as: 'user' %>
      </div>
    <% end %>
  </div>
<% end %>

<h4 class='title is-4 has-text-link'>Future Friends?</h4>

<div class="columns is-multiline">
  <% @users.each do |friend| %>
    <% unless friend == current_user %>
      <% if current_user.possible_friend?(friend) %>
        <div class='column is-3-widescreen is-4-desktop is-6-tablet is-12-mobile'>
          <%= render partial: "user_col", object: friend, as: 'user' %>
          <%= link_to(user_friend_requests_path(friend.id), method: :post, class:'button is-rounded is-small is-primary is-light') do %>
            <span class="icon">
              <i class="fa fa-plus is-small"></i>
            </span>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<article class="media box has-background-primary-light">
  <figure class="media-left">
    <p class="image is-96x96">
      <%= image_tag  @user.avatar.url, class: 'is-rounded' %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong class='title is-1'><%= @user.name %></strong>
        <br>
        <small><%= "@#{@user.handle}" %></small>
      </p>
    </div>
  </div>
  <div class="media-right">
  </div>
</article>

<nav class="level is-mobile">
  <div class="level-left">

    <% if @user == current_user %>
      <%= link_to(users_path, class: 'button level-item is-rounded is-link') do %>
        <span class="icon">
           <i class="fas fa-user-friends"></i>
        </span>
        <span>friends</span>
      <% end %>
      <%= link_to(edit_user_registration_path(current_user), class: 'button level-item is-rounded') do %>
        <span class="icon">
           <i class="fas fa-cog"></i>
        </span>
        <span>edit profile</span>
      <% end %>
    <% else %>
      <% if !FriendRequest.reacted?(current_user.id, @user.id) %>
        <%= link_to(user_friend_requests_path(@user.id), method: :post, class: 'button level-item is-rounded is-success') do %>
          <span class="icon">
           <i class="fas fa-plus"></i>
          </span>
          <span>add friend</span>
        <% end %>
      <% end %>
    <% end %>
  </div>
</nav>

<h4 class='title is-4 has-text-link'>Posts</h4>

<% posts = @user.posts.all.order("created_at DESC") %>
<%= render partial: "posts/post", collection: posts %>