config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => "registrations" }
  
  resources :users, only: [:show, :index] do
    resources :friend_requests, only: [:create] do
      collection do
        get 'accept'
        get 'decline'
      end
    end
  end

  resources :friend_requests do

  end
  
  resources :posts do
    resources :likes, only: [:create]
  end

  resources :comments do
    resources :likes, only: [:create]
  end

  resources :notifications, only: [:index, :destroy]
  
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :author, class_name: "User"
  has_many :comments, class_name: "Comment", foreign_key: "post_id",
  dependent: :destroy
  has_many :likes, dependent: :destroy

  validate :image_size

  def like_count
    self.likes.count
  end

  def comment_count
    self.comments.count
  end

  private

  def image_size
    errors.add(:image, 'should be smaller than 1MB') if image.size > 1.megabytes
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order("created_at DESC").includes(:author, :comments)
  end

  def show 
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    
    if @post.update!
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :image, :image_cache, :remove_image)
  end
end

app/views/posts/_form.html.erb
<%= form_for(:post, url: posts_path, remote: true, :multipart => true) do |f| %>
<div class='field'>
  <div class='control'>
    <%= f.text_area :body, class: "textarea is-info-light", placeholder: "What's on your mind?" %>
  </div>
</div>
<div class='field is-grouped'>
  <div class='control'>
    <%= f.submit "Post", name: nil, class: "button is-success is-small px-6" %>
  </div>
  <div class='control'>
    <div class="file is-info is-light is-small">
      <label class="file-label">
        <%= f.file_field :image, class: "file-input", accept: 'image/jpeg,image/png,image/gif' %>
        <span class="file-cta px-3">
          <span class="file-icon">
            <i class="fas fa-upload"></i>
          </span>
          <span class="file-label">
            Pics?
          </span>
        </span>
      </label>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<article class="media">
  <figure class="media-left is-hidden-touch">
    <p class="image is-64x64">
      <%= image_tag post.author.avatar.feed.url, class: 'is-rounded' %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <% if post.author.handle == "" %>
          <strong><%= link_to  post.author.name,  user_path(post.author.id)%></strong>
        <% else %>
          <strong><%= link_to  post.author.handle, user_path(post.author.id) %></strong>
        <% end %>
        <small>time_ago</small>
        <br>
        <% unless post.image.url.nil? %>
          <figure class="image my-1 mx-0">
            <%= image_tag post.image.url, class: 'feed_post_image' %>
          </figure>
        <% end %>
        <%= post.body %>
        </br>
        <small>
        <%= link_to(new_comment_path(post_id: post.id)) do %>
          <span class="icon is-small"><i class="fas fa-comment"></i></span>
        <% end %>
        <% if !post.comment_count.zero? %>
          <%= post.comment_count %>
        <% end %>
        <%= link_to(post_likes_path(post.id), method: :post) do %>
          <span class="icon is-small"><i class="fas fa-heart"></i></span>
        <% end %>
        <% if !post.like_count.zero? %>
          <%= post.like_count %>
        <% end %>
        </small>
      </p>
    </div>
    <% unless current_page?(controller: 'comments', action: 'new') %>
      <% post.comments.each do |comment| %>
        <%= render partial: "comments/comment", object: comment %>
      <% end %>
    <% end %>
  </div>
</article>

app/views/posts/index.html.erb
<h4 class='title is-4 has-text-link'>Your Feed</h4>

<% if !user_signed_in? %>
  <%= link_to  "Please log in to see your feed!", user_sign_in_path %>
<% else %>
  <%= render "form" %></br></br>

  <% if current_user.friends.length.zero? %>
    <%= "Add some " %>
    <%= link_to  "friends", users_path %>
    <%= " to fill out your feed!" %>
    </br></br>
  <% end %>

  <% @posts.each do |post| %>
    <% if post.author == current_user || current_user.friend_with?(post.author) %>
      <%= render partial: "post", object: post %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h3><%= "#{@post.author.handle}'s Post'"%></h3>

<% unless @post.image.url.nil? %>
  </br>
  <%= image_tag  @post.image.url, class: 'feed_post_image' %>
  </br>
<% end %>

<%= @post.body%></br>
<%= link_to  "comment", new_comment_path(post_id: @post.id) %>
<%= link_to  "like", post_likes_path(@post.id), method: :post %>
<% if !@post.like_count.zero? %>
    <%= "+#{@post.like_count}"%>
<% end %>
</br></br>
<em><%= "posted #{@post.created_at}" %></em>

<% @post.comments.each do |c| %>
    <div class="comment">  
      <% if c.author.handle == "" %>
        <%= link_to  c.author.name,  user_path(c.author.id)%>
      <% else %>
        <%= link_to  c.author.handle, user_path(c.author.id) %>
      <% end %>
      </br>
      <%= c.body %></br>
      <%= link_to  "like", comment_likes_path(c.id), method: :post %>
      <% if !c.like_count.zero? %>
        <%= "+#{c.like_count}"%>
      <% end %></br>
    </div>
  <% end %>