config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => "registrations" }
  
  resources :users, only: [:show, :index] do
    resources :friend_requests, only: [:create] do
      collection do
        get 'accept'
        get 'decline'
      end
    end
  end

  resources :friend_requests do

  end
  
  resources :posts do
    resources :likes, only: [:create]
  end

  resources :comments do
    resources :likes, only: [:create]
  end

  resources :notifications, only: [:index, :destroy]
  
  root "posts#index"
end

app/views/layouts/_menu.html.erb
<aside class="menu" id='nav-menu'>
  <ul class="menu-list">
    <% if user_signed_in? %>
    <% n_count = current_user.notifications.count %>
    <% n_display = n_count.zero? ? nil : " +#{n_count}" %>
    <li>
      <a class='pt-0'>
      <span class='icon is-size-3-touch has-text-danger'><i class='fas fa-meteor'></i></span>
      <span class='title is-5 has-text-link-dark is-hidden-touch'>florpbook</span>
      </a>
    </li>
    <li>
      <%= link_to(posts_path) do %>
      <span class='icon is-size-3-touch has-text-link'><i class='fas fa-home'></i></span>
      <span class='is-hidden-touch'>Home</span>
      <% end %>
    </li>
    <li>
      <%= link_to(notifications_path) do %>
      <span class='icon is-size-3-touch has-text-link'><i class='fas fa-bell'></i></span>
      <span class='is-hidden-touch'><%= "Notifications#{n_display}" %></span>
      <% end %>
    </li>
    <li>
      <%= link_to(user_path(current_user)) do %>
      <span class='icon is-size-3-touch has-text-link'><i class='fas fa-id-badge'></i></span>
      <span class='is-hidden-touch'>Profile</span>
      <% end %>
    </li>
    <li>
      <%= link_to(users_path) do %>
      <span class='icon is-size-3-touch has-text-link'><i class='fas fa-user-friends'></i></span>
      <span class='is-hidden-touch'>Friends</span>
      <% end %>
    </li>
    <li>
      <%= link_to(destroy_user_session_path, :method => :delete) do %>
      <span class='icon is-size-3-touch has-text-link'><i class='fas fa-sign-out-alt'></i></span>
      <span class='is-hidden-touch'>Log Out</span>
      <% end %>
    </li>
    <% else %>
    <li>
      <%= link_to(new_user_session_path) do %>
      <span class='icon is-size-3-touch has-text-link'><i class='fas fa-sign-in-alt'></i></span>
      <span class='is-hidden-touch'>Log In</span>
      <% end %>
    </li>
    <li>
      <%= link_to(new_user_registration_path) do %>
      <span class='icon is-size-3-touch has-text-link'><i class='fas fa-user-plus'></i></span>
      <span class='is-hidden-touch'>Sign Up</span>
      <% end %>
    </li>
    <% end %>
  </ul>
</aside>

app/views/layouts/_navbar.html.erb
<nav class='navbar is-fixed-top is-link'>
  <div class='navbar-brand'>
    <div class='navbar-item'>florpbook</div>
    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div class='navbar-menu' id='navMenu'>
    <div class='navbar-start'>
      <% if user_signed_in? %>
      <% n_count = current_user.notifications.count %>
      <% n_display = n_count.zero? ? nil : " +#{n_count}" %>
      <%= link_to  "Home", posts_path, class: "navbar-item" %>
      <%= link_to  "Notifications#{n_display}", notifications_path, class: "navbar-item" %>
      <%= link_to  "Profile" , user_path(current_user), class: "navbar-item" %>
      <%= link_to 'Friends', users_path, class: "navbar-item" %>
      <% else %>
      <%= link_to  "Log In", new_user_session_path, class: "navbar-item" %>
      <%= link_to  "Sign Up", new_user_registration_path, class: "navbar-item" %>
      <% end %>
    </div>

    <div class='navbar-end'>
    <% if user_signed_in? %>
      <%= link_to  "Log Out", destroy_user_session_path, :method => :delete, class: "navbar-item" %>
    <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

  <title>Florpbook</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class='has-background-link-light'>

    <% if flash[:notice] %>
    <div class="flash_notifcation">
      <p class="good"><%= flash[:notice] %></p>
    </div>
    <% end %>

    <% if flash[:fail] %>
    <div class="flash_notification">
      <p class="bad"><%= flash[:fail] %></p>
    </div>
    <% end %>

    <% if false %>
    <%= render "layouts/navbar" %>
    <% end %>

    <% if false %>
    <div class='columns' id='header-container'>
      <div class='column is-8 is-offset-2 is-flex is-flex-direction-row is-align-content-center'>
        <h2 class='title is-2 has-text-link-dark'>florpbook</h2>
        <span class='icon is-size-4 ml-2 has-text-danger'><i class='fas fa-meteor'></i></span>
      </div>
    </div>
    <% end %>

  <!-- main -->
  <section class='section pt-4'>
    <div class='container'>
      <div class="columns is-mobile" id='main-container'>
        <div class="column is-2" id='menu-container'>
          <%= render "layouts/menu" %>
        </div>
        <div class="column is-10-mobile is-8-desktop" id='feed-container'>
          <%= yield %>
        </div>
      </div>
    </div>
  </section>
  <!-- /main -->
  
  

</body>
<script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>

</html>